language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: FLAGS="CC=clang-5.0 CXX=clang++-5.0 LDFLAGS=-fuse-ld=lld"
    - os: osx
      env: FLAGS=

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - libc6-i386
      - clang-5.0
      - lld-5.0

script:
  - make $FLAGS check

notifications:
  irc:
    channels:
      - "irc.choopa.net#ez80-dev"
    on_success: change
    on_failure: always
    skip_join: true
